# This file was autogenerated.
use 5.008008;
use strict;
use warnings;

use Test::More 0.96;
use Test::Fatal;

use Hydrogen::Topic::CodeRef;

isa_ok( 'Hydrogen::Topic::CodeRef', 'Exporter::Tiny' );

my %EXPORTS = map +( $_ => 1 ), @Hydrogen::Topic::CodeRef::EXPORT_OK;

subtest 'execute' => sub {
    ok exists(&Hydrogen::Topic::CodeRef::execute), 'function exists';
    ok $EXPORTS{'execute'}, 'function is importable';
    my $e = exception {
        local $_;
        my $coderef = sub { 'code' };
        $_ = $coderef;
        
        # $coderef->( 1, 2, 3 )
        Hydrogen::Topic::CodeRef::execute( 1, 2, 3 );
    };
    is $e, undef, 'no exception thrown running execute example';
};

# :)
done_testing;
